# Lesson 3d – Pandas Advanced Operations

**Author:** Alexandre Nordin

## Goals
- Perform advanced group-based analysis
- Use aggregation functions effectively
- Understand apply, map and vectorization
- Write expressive and readable Pandas code

In [1]:
import pandas as pd

# load database
df = pd.read_csv("data/titanic.csv")

In [ ]:
# Grouping by Class to aggregate methrics
df.groupby("Pclass")["Fare"].agg(["mean", "median", "count"])

             mean   median  count
Pclass
1       84.154687  60.2875    216
2       20.662183  14.2500    184
3       13.675550   8.0500    491

In [3]:
# Grouping by multiples fields, cross dimensions get mean of survivors
df.groupby(["Sex", "Pclass"])["Survived"].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [4]:
# Ordering and ranking (comparative analyses)
df.sort_values("Fare", ascending=False).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C

In [ ]:
# Creating a rank by Fare
# Create a new field to ranking by Fare
df["Fare Ranking"] = df["Fare"].rank(ascending=False)
# Ordering by Rank
df.sort_values("Fare Ranking", ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare Ranking
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,884.0
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S,884.0
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0000,B94,S,884.0
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,NaN,S,884.0
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0000,NaN,S,884.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,5.5
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S,5.5
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,2.0
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,2.0
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,2.0

In [15]:
# Create new field to categorize the sex field
# That is important to ML models, allways use number or binarys types in the fiels you will use in ML algorithms
df["SexCode"] = df["Sex"].map({"male": 0, "female": 1})

df[["Name", "SexCode", "Sex"]].head()

                                                Name  SexCode     Sex
0                            Braund, Mr. Owen Harris        0    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        1  female
2                             Heikkinen, Miss. Laina        1  female
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        1  female
4                           Allen, Mr. William Henry        0    male

In [ ]:
# Vetorized operation
# Always use this instead of loops
# Creatind  new field with the Fared mean by family
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["FarePerPerson"] = df["Fare"] / df["FamilySize"]
# Print Name ordering by Family Size
df[["FamilySize", "Name"]].sort_values(by="FamilySize", ascending=False)

     FamilySize                              Name
846          11          Sage, Mr. Douglas Bullen
324          11          Sage, Mr. George John Jr
792          11           Sage, Miss. Stella Anna
180          11      Sage, Miss. Constance Gladys
159          11        Sage, Master. Thomas Henry
..          ...                               ...
876           1     Gustafsson, Mr. Alfred Ossian
875           1  Najib, Miss. Adele Kiamie "Jane"
873           1       Vander Cruyssen, Mr. Victor
872           1          Carlsson, Mr. Frans Olof
870           1                 Balkic, Mr. Cerin

[891 rows x 2 columns]

In [ ]:
# Create a category to Fare
df["FareCategory"] = df.apply(
    lambda row: "High" if row["Fare"] > df["Fare"].median() else "Low",
    axis=1
)
# Print name and Fare Category
df[["Name", "FareCategory"]].head()
# Survived by Fare Category
df.groupby("FareCategory")["Survived"].mean()
# The surve chance is bigger the the Fare was High

FareCategory
High    0.518018
Low     0.250559
Name: Survived, dtype: float64

In [ ]:
# Converting to category type
df["Pclass"] = df["Pclass"].astype("category")

df[["Pclass", "Name"]].head()
# we use the Category Type to:
# Less memory
# Cear semantic
# Better reading

# Checkink Data Types
df.dtypes

PassengerId         int64
Survived            int64
Pclass           category
Name                  str
Sex                   str
Age               float64
SibSp               int64
Parch               int64
Ticket                str
Fare              float64
Cabin                 str
Embarked              str
Fare Ranking      float64
SecCode             int64
SexCode             int64
FamilySize          int64
FarePerPerson     float64
FareCategory          str
dtype: object

In [ ]:
# seting Index
df.set_index("PassengerId", inplace=True)
# Index is very important to better performance

# Reset the index
df.reset_index(inplace=True)

In [ ]:
# Using chaining Method
(
    df
    .assign(IsHighFare=lambda x: x["Fare"] > x["Fare"].median())
    .groupby("IsHighFare")["Survived"]
    .mean()
)
# Calculate the chance to survive if you is High Fare and if not High Fare

IsHighFare
False    0.250559
True     0.518018
Name: Survived, dtype: float64

### Key Insights – Pandas Advanced Operations

Advanced Pandas operations allow complex analytical questions
to be answered with concise and expressive code.

Understanding grouping, aggregation, and vectorized operations
is essential to writing scalable and maintainable Data Science workflows.